services:
  mongodb:
    image: mongo:6-jammy
    hostname: mongodbbox
    networks:
      - mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  mojo:
    build: .
    networks:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  dbdata6:

networks:
  mongo:
    driver: bridge
